In [3]:
## Decision Tree Regression
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
print(iris['DESCR'])
print(iris['target'])
x = pd.DataFrame(iris['data'],columns=['sepal length in cm','sepal width','petal length','petal width'])
print(x)
y = iris['target']
print(y)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

from sklearn.tree import DecisionTreeRegressor
dtc = DecisionTreeRegressor()
dtc.fit(x_train,y_train)
y_pred = dtc.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy : ",accuracy_score(y_test,y_pred))
print("Confusion Matrix : \n",confusion_matrix(y_test,y_pred))
print("classfication Report :\n ",classification_report(y_test,y_pred))

Accuracy :  1.0
Confusion Matrix : 
 [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
classfication Report :
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [5]:
# decision tree regressor with pre-pruning and hyper parameter tuning
param = {
    'criterion' : ["squared_error", "absolute_error"],
    'splitter' : ['best', 'random'],
    'max_depth' : [1, 2, 3, 4, 5],
    'max_features' : ['auto', 'sqrt', 'log2']
}
print(param)
from sklearn.model_selection import GridSearchCV
tree_model = DecisionTreeRegressor()
grid = GridSearchCV(dtc, param_grid=param, cv = 5, scoring='accuracy')
import warnings
warnings.filterwarnings('ignore')
grid.fit(x_train,y_train)
grid.best_params_
y_pred1 = grid.predict(x_test)
print(y_pred1)
print("Accuracy : ",accuracy_score(y_test,y_pred1))
print("Confusion Matrix : \n",confusion_matrix(y_test,y_pred1))
print("classfication Report :\n ",classification_report(y_test,y_pred1))


{'criterion': ['squared_error', 'absolute_error'], 'splitter': ['best', 'random'], 'max_depth': [1, 2, 3, 4, 5], 'max_features': ['auto', 'sqrt', 'log2']}
[1. 0. 2. 1. 2. 0. 1. 2. 1. 1. 2. 0. 0. 0. 0. 1. 2. 1. 1. 2. 0. 2. 0. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 1. 0. 0. 2. 1. 0.]
Accuracy :  0.9736842105263158
Confusion Matrix : 
 [[15  0  0]
 [ 0 10  1]
 [ 0  0 12]]
classfication Report :
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.91      0.95        11
           2       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

